OpenMined/SyferText

- syfertext/vectors.py
- tests/local_mode/test_language.py
> Error when requesting a vector for out-of-vocabulary tokens

- syfertext/doc.py
- syfertext/token.py
- syfertext/tokenizer.py
- syfertext/vectors.py
- Doc's `get_encrypted_vector` method now considers only tokens that have vectors.
- Added the  `has_vector` attribute to Token objects.
> Compute Doc vectors as an average of only in-vocabulary token vectors

- .github/PULL_REQUEST_TEMPLATE.md
> Add PR checklist

- syfertext/language.py
- syfertext/tokenizer.py
- syfertext/vectors.py
- syfertext/vocab.py
> small typo

- setup.py
Added compatibility with syft v0.2.4
> Update SyferText version to 0.1.0dev2

- syfertext/utils.py
Updated the download links for "en_core_web_lg"
Fixes #70
All current tests
> Updated language model download links

- syfertext/string_store.py
- syfertext/vocab.py
- tests/local_mode/test_store.py
removed pre-loaded strings in StringStore. Now string will only be added when it is encountered first.
Fixes #59
> Removed pre-loaded strings in StringStore

- syfertext/language.py
- syfertext/pointers/__init__.py
- tests/distributed_mode/test_pipeline.py
Tests for pipeline functionality. #40 
I also added/modified some docs and added examples to help readers & developers understand the design of SyferText's pipeline.
> Added tests for pipeline

- syfertext/tokenizer.py
return empty doc([]) for empty strings ("")
Fixes #76 
> tokenize empty strings

- tutorials/Part 2 - (Getting Started) Using SimpleTagger.ipynb
This PR will add a tutorial for the SimpleTagger pipeline component.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> Add tutorial for SimpleTagger

- setup.py
- Updated setup to point to Syft's version 0.2.5 on PyPI
- Updated SyferText version to 0.0.1 as @Nilanshrajput suggested
> Updated setup.py to point to Syft on PyPI

- setup.py
- syfertext/__init__.py
- syfertext/doc.py
- syfertext/language.py
- syfertext/pipeline/pointers/subpipeline_pointer.py
- syfertext/pipeline/subpipeline.py
- syfertext/pointers/doc_pointer.py
- syfertext/pointers/span_pointer.py
- syfertext/span.py
- syfertext/token.py
- syfertext/tokenizer.py
- tests/local_mode/test_doc.py
I prepared for support to syft v0.2.7. Serde module in PyPI's v0.2.6 has an issue that was fixed later. The issue is important to register external libraries. So I skipped 0.2.6
Another issue with syft's PyPI v0.2.6 was fixed here:
https://github.com/OpenMined/PySyft/pull/3642
So I pointed setup.py to a specific commit in the master repo. This should be changed when Syft v0.2.7 is out.
Existing tests
> Prepared support for future syft v0.2.7

- README.md
Add support section at README.md with the proper links to OM slack channels.
- [*] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [* ] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [* ] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [* ] My changes are covered by tests
> Add support section at README.md 

- syfertext/doc.py
- syfertext/lexeme.py
- syfertext/pointers/doc_pointer.py
- syfertext/token.py
- syfertext/vectors.py
- tests/local_mode/test_doc.py
- tests/local_mode/test_language.py
- tests/local_mode/test_lexeme.py
- tests/local_mode/test_token.py
- tests/local_mode/test_token_attributes.py
This pull request is related to issue #100 for Replacing Numpy arrays by torch tensors
> Replace Numpy arrays by torch tensors

- setup.py
syft pointing to PySyft https://github.com/OpenMined/PySyft@bc5337507047b325e79cb9b2060abac4bdc08f3f"
> Update Pysyft version 0.2.7 on master

- setup.py
To maintain stability with PyGrid, syft required for SyferText should be consistent with PyGrid
Please include a summary of the change, the motivation, and any additionl context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
List any dependencies that are required for this change.
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.
- [ x I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
> update syft version pypi release

- syfertext/__init__.py
- syfertext/doc.py
- syfertext/language.py
- syfertext/pipeline/pointers/subpipeline_pointer.py
- syfertext/pipeline/single_label_classifier.py
- syfertext/pipeline/subpipeline.py
- syfertext/pointers/doc_pointer.py
Support for using SingleLabelClassifier for inference remotely without downloading it to the data owner's node.
- Tests are needed (see #178)
> Implemented remote inference for SingleLabelClassifier

- syfertext/tokenizer.py
- tutorials/Part 0 - (Getting Started) Local Tokenization.ipynb
Default tokenization rules were not working when creating a tokenizer with default arguments
> Fixed tokenization bug

- setup.py
- syfertext/doc.py
- syfertext/language.py
- syfertext/pipeline/pointers/pipeline_pointer.py
- syfertext/pipeline/single_label_classifier.py
- syfertext/pointers/doc_pointer.py
Update SyferText for Pygrid compatibility
Got tutorials running on grid nodes,
add protocol commands for encrypted vectors
Black version updates to 20.8b1 and Pysyft to 0.2.9
> Grid update

- syfertext/pipeline/pointers/pipeline_pointer.py
- syfertext/pointers/state_pointer.py
register requested state and pipeline from remote worker locally
> Register state and pipeline from remote worker

- setup.py
- syfertext/pipeline/average_doc_encoder.py
- syfertext/pipeline/single_label_classifier.py
Add protocol in avg_doc_encoder and correct pysyft install link
> Small_patch

- tests/local_mode/test_pipeline.py
Fixes #177
Please review.
@AlanAboudib I am still not sure how a pipeline is being reused. Can you give a small example in code so that I could improve the tests further.
Currently it is looking pretty similar to `distributed_mode/test_pipeline.py`
Also if there is anything more you would like me to add, please feel free.
> Add pipeline parsing tests
