OpenMined/SyferText

- .gitignore
- syfertext/language.py
- syfertext/pointers/doc_pointer.py
This PR closes #1. It allows the `Language` class to track the tokenizers that have been created for each remote worker so they can be re-used down the line.
> Tokenizer tracking for remote workers

- setup.py
Upgrades PySyft version to `0.2.3.a3` to avoid `UndefinedProtocolTypeError`.
> Fixed UndefinedProtocolTypeError for PySyft dependency

- .github/workflows/main.yml
- setup.py
- syfertext/doc.py
- syfertext/pipeline/__init__.py
- syfertext/pipeline/simple_tagger.py
- syfertext/token.py
- syfertext/tokenizer.py
- syfertext/underscore.py
- tests/local_mode/test_simple_tagger.py
I added a class called `SimpleTagger` in a new module called `pipeline`. This object can be called on a `Doc` object. It creates a custom attribute for each of its tokens. This attributes holds a tag. The tokens to be tagged are specified in the initialization of the `SimpleTagger` object.
Example usage:
```
from syfertext.pipeline import SimpleTagger
doc = nlp("I liKe things")
tagger = SimpleTagger(attribute= 'is_stop',
lookups= {"I": 'net', 'liKe': 2},
case_sensitive= True,
tag=True,
default_tag='unknown')
tagger(doc)
print(doc[0]._.is_stop)
print(doc[2]._.is_stop)
```
This class can be useful in order to mark certain tokens as stop words for instance. This is just an example but the possibilities are numerous.
> Created SimpleTagger class

- syfertext/doc.py
- tests/local_mode/test_custom_doc_attr.py
- tests/local_mode/test_doc.py
Add support for adding custom attribute to Doc objects
Fixes #30  
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
```python
me = hook.local_worker
nlp = syfertext.load('en_core_web_lg', owner = me)
doc = nlp("Tokenize me")
doc.set_attribute(name = 'hello', value = 'tag')
print(doc._.hello)
#output tag
```
> added custom attr

- syfertext/doc.py
- tests/local_mode/test_doc.py
Add the get_vector method to ignore tokens when getting the average vector of the doc.
If your pull request closes a GitHub issue, then set its number below.
Fixes #43 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> added the get_vector() method with excluded_tokens argument

- syfertext/language.py
Since `_parse_pipeline_template` is already included in `_reset_pipeline` , it is no longer required here.
> remove line

- syfertext/utils.py
- tests/local_mode/test_language.py
Every time the downloading of a model fails (for various reasons) we have to remove the `~/SyferText` data folder because `SyferText` tries to retrieve non-existing files in our next attempt to get the model. I ran into this issue multiple times because of the relatively slow connection on my local setup.
I solved the issue by first downloading the model into a temporary path, then only after successfully downloading the files they are moved to `~/SyferText`.
Fixes #51 
Please mark the options that are relevant.
We can reproduce the problem by interrupting the download process.
I tested the new edits using the notebook's cell:
```Python
nlp = syfertext.load('en_core_web_lg', owner = me)
type(nlp), nlp.owner
```
On the following cases:
- Without a data path
- With a data path but by …
> Model download -> tmp path -> data path

- syfertext/doc.py
- syfertext/pipeline/subpipeline.py
- syfertext/tokenizer.py
- tests/local_mode/test_doc.py
Fixes #73 
We can explicitly assign the `doc.owner = self.owner` when we know that the doc is on a remote worker
@AlanAboudib your review would be helpful
> doc owner fix

- syfertext/pipeline/subpipeline.py
Remove owner assignment to the `Doc` object at the end of the `__call__` method of the `SubPipeline` class. The owner is assigned correctly in #74
> Some cleaning

- syfertext/doc.py
- syfertext/token.py
- tests/local_mode/test_doc.py
- tests/local_mode/test_token.py
I just thought it would be a nice addition to include similarity between tokens.
I have added similarity between docs as well on the basis of averaged token vectors.
```python
doc1 = nlp("hello banana")
doc2 = nlp("artic monkeys")
token1 = doc1[0]
token2 = doc1[1]
token1.vector_norm 
token1.similarity(token2)
doc1.vector_norm
doc1.similarity(doc2)
```
> Added similarity of documents and tokens

- syfertext/doc.py
- syfertext/pointers/doc_pointer.py
- syfertext/span.py
Added `_get_valid_tokens(excluded_tokens)`, a central place to handle all logic related to excluding tokens for `Doc` and `Span`. `_get_valid_tokens` returns a **generator** which yields valid tokens (tokens which are not to be excluded).
- Makes the code more readable, and much fewer lines.
- Gives us a central location to handle excluding tokens, and can be extended to include other methods of excluding tokens.
Existing tests.
> Added _get_valid_tokens() to Doc and Span

- README.md
Removing the all contributors badge as the display on GitHub is not proper.
> Remove all-contributors badge

- setup.py
Updated versions for SyferText_0.1.0 for issue #139
> update SyferText.py 

- syfertext/language.py
- syfertext/pipeline/subpipeline.py
- syfertext/vectors.py
- syfertext/vocab.py
This PR improves code to add support to adding vectors to Vocab objects at the moment of initialization. Making sure that loading and dumping `Vocab` states is functional.
However, as opposed to what is mentioned in #138, no `key2row` or `vectors` arguments are added to the `Language.set_vocab()` is added since this is not needed.
Closes #138 
None
- Tests are coming soon
> Added support for loading vectors to Vocab

- syfertext/pipeline/simple_tagger.py
- syfertext/pipeline/subpipeline.py
- syfertext/tokenizer.py
- syfertext/utils.py
The Proto id generated on different workers were different, so now the code is generated using the  hash of the class name
- [ x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [ x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [ x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [ x] My changes are covered by tests
> Proto id generation update 

- README.md
- setup.py
- syfertext/doc.py
- syfertext/language.py
- syfertext/lexeme.py
- syfertext/pipeline/simple_tagger.py
- syfertext/span.py
- syfertext/string_store.py
- syfertext/token.py
- syfertext/tokenizer.py
- syfertext/underscore.py
- syfertext/utils.py
- syfertext/vocab.py
- tests/local_mode/test_span.py
Corrects the missing closing parenthesis in the introductory paragraph of the readme
None
- Correction is rendered correctly in GitHub readme
> fix: Adds missing parenthesis in readme

- syfertext/__init__.py
- syfertext/language.py
Pipeline parsing into subpipelines was not functional when pipe components had different permissions. This is fixed now.
Also, when a pipeline is parsed for multiple data owners, this could result in identical subpipelines among different data owner, in order to reduce redundancy, I implemented subpipeline reuse.
- Tested are needed (see issue #177)
I hadn't implemented unit tests yet. Merging this PR is urgent for #pricon2020
> Fixed pipeline parsing and  implemented SubPipeline reuse

- syfertext/pointers/doc_pointer.py
- syfertext/pointers/span_pointer.py
- tests/local_mode/test_span.py
- Removed ```__len__``` from SpanPointer and DocPointer
- Removed assert statements on len for SpanPointer and DocPointer from tests
- Ran all tests successfully
> Fixes Issue 152

- syfertext/pipeline/pointers/pipeline_pointer.py
- syfertext/pointers/state_pointer.py
To Persist pipeline remotely, updated get_copy functions in state and pipeline pointers, this change is in consideration after my latest change in PySyft `get()` method https://github.com/OpenMined/PySyft/pull/4633 where new `get_copy` argument is added in `get()` method and related functions for getting objects without removing the remote object.
none
Not covered
> Persist pipeline and states remotely, updated get_copy

- syfertext/doc.py
- syfertext/token.py
- syfertext/vectors.py
- tests/local_mode/test_doc.py
When returning a single vector in the `__getitem__` method of the `Vector` class, the tensor should be of shape (1, <number of coefficient>) rather than (<number of coefficient>,).
This fix is necessary for correct functionality of torch ops such as applying a linear layer in inference.
> fix for vector shapes

- .github/workflows/main.yml
- setup.py
- syfertext/__init__.py
- syfertext/language.py
- syfertext/pipeline/pipeline.py
remove state objects from pipeline only description dictionary of dictionaries containing the description of each state needed to reconstruct the pipeline.
Also updated the pysyft to master branch(0.2.9)
Fixed python = 3.7 in CI build
none
> Remove state objects from pipeline 
